// Generated by Wrangler on Tue Jul 02 2024 13:25:45 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	AI: Ai;
}
